# Generated by Django 6.1 on 2026-08-27 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_product_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='artisan',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
